In [4]:
import numpy as np
a = np.random.randint(10, size=(3, 4))
b = np.random.randint(10, size=(3, 4))

a.ndim

2

## Resources

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
#output if we use GPU
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

###Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([1.0, 2.0])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([
    [1, 2, 14],
    [3, 4, 10],
    [5, 6, 12],
    [7, 8, 17]])

In [ ]:
MATRIX

tensor([[ 1,  2, 14],
        [ 3,  4, 10],
        [ 5,  6, 12],
        [ 7,  8, 17]])

In [ ]:
MATRIX.shape

torch.Size([4, 3])

In [ ]:
# [[ this brackts denots dimention think logically ]]
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([ 1,  2, 14])

In [ ]:
#tensor
TENSOR = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR2 = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[1, 2, 3],
     [3, 2, 1],
     [8, 0, 5]]
])

In [ ]:
TENSOR2.shape

torch.Size([2, 3, 3])

## Random Tensors

In [ ]:
torch.rand(4)

tensor([0.5630, 0.1613, 0.2043, 0.9719])

In [ ]:
torch.rand(4,3)

tensor([[0.1595, 0.2760, 0.1269],
        [0.4153, 0.0231, 0.1682],
        [0.5063, 0.6617, 0.1948],
        [0.5451, 0.5142, 0.8366]])

In [ ]:
torch.rand(
    size=(2, 3, 4),
    dtype=torch.float16
)

tensor([[[0.0625, 0.9668, 0.1475, 0.2051],
         [0.5757, 0.4746, 0.4351, 0.6836],
         [0.1802, 0.7505, 0.8384, 0.4165]],

        [[0.2754, 0.7427, 0.0688, 0.4082],
         [0.4771, 0.1582, 0.5010, 0.2188],
         [0.8003, 0.4971, 0.9526, 0.8691]]], dtype=torch.float16)

In [ ]:
torch.rand(
    size=(2, 3, 4),
    dtype=torch.complex64
  )


tensor([[[0.7557+0.9347j, 0.9135+0.8563j, 0.3241+0.8869j, 0.7534+0.9137j],
         [0.4904+0.8111j, 0.7405+0.5930j, 0.6862+0.6129j, 0.8527+0.5927j],
         [0.8216+0.4907j, 0.8414+0.1397j, 0.6383+0.1010j, 0.1577+0.5277j]],

        [[0.7320+0.0061j, 0.8190+0.0769j, 0.6648+0.2942j, 0.1926+0.9649j],
         [0.2291+0.4826j, 0.9120+0.6157j, 0.4480+0.1959j, 0.0727+0.0870j],
         [0.7615+0.5433j, 0.5018+0.0960j, 0.3757+0.9916j, 0.0630+0.5374j]]])

In [ ]:
torch.randint(
    size=(2, 3, 4),
    low=0,
    high=10
)

tensor([[[1, 8, 0, 6],
         [2, 0, 1, 3],
         [5, 9, 0, 4]],

        [[9, 1, 3, 8],
         [5, 8, 3, 1],
         [1, 2, 6, 9]]])

In [ ]:
#create a random tensor with similar shape to image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))   #height , width , colour(R,G,B) channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensor

In [ ]:
torch.zeros(size=(3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones(size=(3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## creating a range of tensor and tensor-like

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
multipliy_3 = torch.arange(start=3, end=31, step=3) #fun way of generating a multiplication

In [ ]:
for i,mul in enumerate(multipliy_3, start=1):  #enumerate
  print(f'3 * {i} = {mul}')

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30


In [ ]:
multipliy_3

tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
torch.zeros_like(input=multipliy_3)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data type

**Note:** Tensor datatype is one of the 3 error you will encounter with Pytorch and deep learning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
float_32 = torch.tensor(
    [3.1, 6, 9],
    dtype=None,
    device=None,  #which device is your tensor on
    requires_grad=False   #to track gradient or not with this tensor
  )

float_32, float_32.dtype, float_32.device

(tensor([3.1000, 6.0000, 9.0000]), torch.float32, device(type='cpu'))

In [ ]:
float_32.shape, float_32.ndim, float_32.requires_grad

(torch.Size([3]), 1, False)

In [ ]:
#changing from 32 to 16

float_16 = float_32.type(torch.float16)
float_16,float_16.dtype, float_16.device

(tensor([3.0996, 6.0000, 9.0000], dtype=torch.float16),
 torch.float16,
 device(type='cpu'))

In [ ]:
a = float_32 * float_16
a, a.dtype, a.device

(tensor([ 9.6088, 36.0000, 81.0000]), torch.float32, device(type='cpu'))

In [ ]:
b = float_16 * float_32
b, b.dtype, b.device

(tensor([ 9.6088, 36.0000, 81.0000]), torch.float32, device(type='cpu'))

## Getting Information of tensors

**Note:** Check
 1. Tensor not right datatype - ' tensor.dtype '
 2. Tensor not right shape - ' tensor.shape '
 3. Tensor not on the right device - ' tensor.device '

In [ ]:
B = torch.rand(size=(3, 4))


In [ ]:
B, B.shape, B.dtype, B.device

(tensor([[0.6537, 0.1893, 0.6791, 0.9313],
         [0.9115, 0.8595, 0.7844, 0.3393],
         [0.8388, 0.7093, 0.7105, 0.3901]]),
 torch.Size([3, 4]),
 torch.float32,
 device(type='cpu'))

## Manupalating Tensors (Tensor operations)
Tensors operation Include:
* Addition
* Multipliction (element-wise)
* Subtraction
* Division
* Matrix Multipliction

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [ ]:
a + 10

tensor([11, 12, 13])

In [ ]:
a * 10

tensor([10, 20, 30])

In [ ]:
a / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
a * b

tensor([ 4, 10, 18])

In [ ]:
a + b

tensor([5, 7, 9])

In [ ]:
a - b

tensor([-3, -3, -3])

In [ ]:
a/b

tensor([0.2500, 0.4000, 0.5000])

In [ ]:
torch.multiply(a, b)

tensor([ 4, 10, 18])

In [ ]:
torch.add(a, b)

tensor([5, 7, 9])

In [ ]:
a @ b

tensor(32)

In [ ]:
a = torch.rand(size=( 3, 4))
b = torch.rand(size=( 4, 3))

In [ ]:
a @ b

tensor([[0.8431, 0.6774, 0.7381],
        [1.3968, 0.9567, 1.2058],
        [1.3269, 0.7570, 1.1475]])

In [ ]:
%%time
torch.matmul(a, b)

CPU times: user 174 µs, sys: 0 ns, total: 174 µs
Wall time: 2.2 ms


tensor([[0.8431, 0.6774, 0.7381],
        [1.3968, 0.9567, 1.2058],
        [1.3269, 0.7570, 1.1475]])

In [ ]:
%%time
result = torch.zeros(size=(a.shape[0], b.shape[1]))
for i in range(len(a)):
  for j in range(len(b[0])):
    for k in range(len(b)):
      result[i][j] += a[i][k] * b[k][j]

result

CPU times: user 1.27 ms, sys: 517 µs, total: 1.79 ms
Wall time: 2.03 ms


tensor([[0.8431, 0.6774, 0.7381],
        [1.3968, 0.9567, 1.2058],
        [1.3269, 0.7570, 1.1475]])

In [ ]:
import numpy as np
a = np.array(a)
b = np.array(b)

In [ ]:
%%time
np.matmul(a, b)

CPU times: user 350 µs, sys: 78 µs, total: 428 µs
Wall time: 7.65 ms


array([[0.84310925, 0.6774324 , 0.7380909 ],
       [1.3967509 , 0.95665044, 1.2057754 ],
       [1.3268541 , 0.7570346 , 1.147518  ]], dtype=float32)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

In [ ]:
x_reshape = x.reshape(5, 2)
x_reshape

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Fri Jun  7 18:24:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
torch.cuda.device_count()

1

In [19]:
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.tensor([1, 2, 3], device=device)

tensor([1, 2, 3], device='cuda:0')

In [24]:
a = torch.rand(size=(3, 4), device=device)
b = torch.rand(size=(3, 4), device=device)
torch.mm(a,b.T)

tensor([[1.4376, 1.1717, 1.3490],
        [0.9548, 1.2922, 1.5097],
        [1.2907, 0.9478, 1.2221]], device='cuda:0')